In [17]:
import pandas as pd 
from main import UserPredictor
model = UserPredictor()
%load_ext autoreload
%autoreload 2

In [18]:
train_users = pd.read_csv("data/train_users.csv")
train_logs = pd.read_csv("data/train_logs.csv")
train_y = pd.read_csv("data/train_y.csv")

train_users
train_logs
train_y
model.fit(train_users, train_logs, train_y)

AttributeError: 'UserPredictor' object has no attribute 'categoricals'

In [9]:
train_logs = train_logs.groupby("user_id")["seconds"].sum()

In [12]:
df = pd.merge(train_users, train_logs, how = "left", on = "user_id").fillna(0)
df

       user_id            names  age  past_purchase_amt   badge  seconds
0            0  Adriana Mcclure   26          39.344704    gold    327.0
1            1    Stacy Gilmore   67          15.840151  silver     78.0
2            2     Joanna Walsh   50        1099.420085  bronze    432.0
3            3    Eduardo Moore   65           5.880239  bronze      0.0
4            4   Angela Freeman   88        1312.296847  bronze      0.0
...        ...              ...  ...                ...     ...      ...
29995    29995    William Lewis   87         108.914205  bronze    563.0
29996    29996    James Miranda   49         291.969273    gold    532.0
29997    29997     Carlos Davis   46           2.609698  bronze      0.0
29998    29998    Makayla Smith   23         164.885894  bronze      0.0
29999    29999    Tina Anderson   51         161.905284    gold    467.0

[30000 rows x 6 columns]